// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<EscrowEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EscrowEvent {
    /// "EscrowCreated", "EscrowCompleted", "EscrowRefunded"
    #[prost(string, tag = "1")]
    pub event_type: ::prost::alloc::string::String,
    /// The escrow ID
    #[prost(string, tag = "2")]
    pub escrow_id: ::prost::alloc::string::String,
    /// Buyer address
    #[prost(string, tag = "3")]
    pub buyer: ::prost::alloc::string::String,
    /// Seller address
    #[prost(string, tag = "4")]
    pub seller: ::prost::alloc::string::String,
    /// Amount in wei as string
    #[prost(string, tag = "5")]
    pub amount: ::prost::alloc::string::String,
    /// Transaction hash
    #[prost(string, tag = "6")]
    pub transaction_hash: ::prost::alloc::string::String,
    /// Block number
    #[prost(uint64, tag = "7")]
    pub block_number: u64,
    /// Block timestamp
    #[prost(uint64, tag = "8")]
    pub timestamp: u64,
    /// Escrow contract address
    #[prost(string, tag = "9")]
    pub contract_address: ::prost::alloc::string::String,
}
